use crate::object::{IntoPushedValue, ModuleState, linking::{RelocEntry, Symbol}};
use super::InstructionSink;
use wasm_encoder::BlockType;

impl InstructionSink<'_> {
	pub fn push(&mut self, state: &mut ModuleState, value: impl IntoPushedValue) -> &mut Self {
		value.push(state, self);
		self
	}

	pub fn const_val(&mut self, value: impl Into<value::Value>) -> &mut Self {
		self.i64_const(value.into().as_i64())
	}

	pub fn static_str(&mut self, symbol: Symbol, len: u32) -> &mut Self {
		// These operations are generated by Rust, I've recreated them here so that `wasm-opt`
		// can inline the logic, rather than a function call being required.
		// It is vital these remain up to date with whatever logic the `value` Crate impls.

		//TODO: A large part of these operations recreate the same value.
		//TODO: Requiring a local be passed in may be worthwhile.

		// Sorry about the weird formatting, it makes it easier to follow the flow.
		self
										.i32_const(len.cast_signed())
										.i32_const(24)
									.i32_rotr()
									.i32_const(16711935)
								.i32_and()

										.i32_const(len.cast_signed())
										.i32_const(16711935)
									.i32_and()
									.i32_const(8)
								.i32_rotr()
							.i32_or()
							.i32_const(-256)
						.i32_and()
					.i64_extend_i32_u()

							.push_addr(symbol)
						.i64_extend_i32_u()
						.i64_const(32)
					.i64_shl()
				.i64_or()

										.i32_const(len.cast_signed())
										.i32_const(24)
									.i32_rotr()
									.i32_const(16711935)
								.i32_and()

										.i32_const(len.cast_signed())
										.i32_const(16711935)
									.i32_and()
									.i32_const(8)
								.i32_rotr()
							.i32_or()
							.i32_const(240)
						.i32_and()
						.i32_const(3)
					.i32_or()
				.i64_extend_i32_u()
			.i64_or()
	}

	pub fn push_addr(&mut self, symbol: Symbol) -> &mut Self {
		self
			// We set the address to a placeholder value, MAX to ensure padding.
			.reloc(RelocEntry::i32const_address(symbol))
			.i32_const(i32::MAX)
	}

	pub fn block(&mut self, ty: BlockType) -> &mut Self {
		if let BlockType::FunctionType(ty_idx) = ty {
			return self.reloc(RelocEntry::typed_block(ty_idx))
				.block_raw(ty);
		}

		self.block_raw(ty)
	}

	pub fn loop_(&mut self, ty: BlockType) -> &mut Self {
		if let BlockType::FunctionType(ty_idx) = ty {
			return self.reloc(RelocEntry::typed_block(ty_idx))
				.loop_raw(ty);
		}

		self.loop_raw(ty)
	}

	pub fn if_(&mut self, ty: BlockType) -> &mut Self {
		if let BlockType::FunctionType(ty_idx) = ty {
			return self.reloc(RelocEntry::typed_block(ty_idx))
				.if_raw(ty);
		}

		self.if_raw(ty)
	}

	pub fn call(&mut self, symbol: Symbol) -> &mut Self {
		self.reloc(RelocEntry::function(symbol))
			.call_raw(u32::MAX)
	}

	pub fn call_indirect(&mut self, state: &mut ModuleState) -> &mut Self {
		self.reloc(RelocEntry::indirect_call(state.dyn_call_ty, state.call_tab))
			.call_indirect_raw(u32::MAX, u32::MAX)
	}

	pub fn call_as_lua_fn(&mut self, state: &mut ModuleState) -> &mut Self {
		self.call(state.extern_fns.get_fn)
			.call_indirect(state)
	}

	pub fn global_get(&mut self, symbol: Symbol) -> &mut Self {
		self.reloc(RelocEntry::global(symbol))
			.global_get_raw(u32::MAX)
	}

	pub fn global_set(&mut self, symbol: Symbol) -> &mut Self {
		self.reloc(RelocEntry::global(symbol))
			.global_set_raw(u32::MAX)
	}

	pub fn try_table(&mut self, ty: BlockType, tag: Symbol, label: u32) -> &mut Self {
		self.reloc(RelocEntry::catch_table(tag))
			.try_table_raw(ty, [wasm_encoder::Catch::One { tag: u32::MAX, label }])
	}

	pub fn throw(&mut self, tag_symbol: Symbol) -> &mut Self {
		self.reloc(RelocEntry::throw(tag_symbol))
			.throw_raw(u32::MAX)
	}

	pub fn push_function_ptr(&mut self, _state: &mut ModuleState, closure: Symbol) -> &mut Self {
		self.reloc(RelocEntry::i32const_indirect_fn(closure))
			.i32_const(i32::MAX)
	}

	fn reloc(&mut self, entries: impl IntoIterator<Item = RelocEntry>) -> &mut Self {
		let function_len = self.byte_len();
		for entry in entries {
			self.relocations.push(entry.offset_by(function_len));
		}
		self
	}
}
